### ISSUE TITLE
Parser moduleOrder Modification Bug - Weird DoT Uptime, Language Hijinx, Etc.

### ISSUE THREAD

**Issue by KhloeLeclair** [xivanalysis/xivanalysis#100]
Parser runs a sort operation on `moduleOrder` on the second line of `generateResults()`. Parser should be making a shallow copy of `moduleOrder` before running sort, or sorting directly into a new array.

This probably wouldn't be a major bug, since you're generally done running operations when Parser is generating its results... but what if you're not?

Enter language switching. (And bad assumptions in Analyse. Mostly that.)

Analyse is updating way too often. Changing a language can end up running Analyse's full update path three times because of the language loading state propagating through the app. This is a ridiculous waste and really needs to stop.

So, bad stuff happens. You end up with the `fetchEventsAndParse` method running multiple times in parallel, at different stages. The function, and Analyse overall, is not designed for this. The parser is saved to Analyse's state. At the end of the function, Analyse's state is updated to have `complete: true`. Which is great.

Except that, by then, `parser` has changed and when Analyse calls `getParserResults()`, which calls the parser's `generateResults()`, Parser sorts `moduleOrder` and messes up whatever was still running at that point. Like `normalise`.

In JavaScript, Array iterators do not take a snapshot of the Array. Because the order of `moduleOrder` suddenly changes mid-execution, Parser ends up potentially skipping some Modules' `normalise()` methods entirely while running others multiple times.

Fixes:

1. Never alter a Parser's `moduleOrder` once the value has been initialized.
2. Stop making multiple Parsers and updating Analyse at the drop of a hat.

**Comment by ackwell** [comment]
Fixes pushed. Analyser does a few checks before it decides it should perform a re-parse, but a bad comparison was causing it to be super trigger happy. It should now only ever refresh if it actually needs to load a new report - language changes propagate w/o re-running the parse.

And that fix for the display order is in place. Probably just a logic lapse, too used to arrays copying by value in PHP :blobsweat:.
