### ISSUE TITLE
Grouped tracked actions in Buff Window

### ISSUE THREAD

**Issue by hintxiv** [xivanalysis/xivanalysis#1158]
This modification to core BuffWindow would allow for multiple actions to be grouped into a single tracked action, i.e. a single column in the table, to reduce bloat.

An example use case is GNB's cart combo - we would want 1 of each combo GCD and 1 of each continuation for a perfect 6/6 under a particular buff (No Mercy, Tincture).

**Comment by ayyaruq** [comment]
Relevant to TCJ on NIN as well. Tagged as requested.

**Comment by ayyaruq** [comment]
`ExpectedActionGroupsEvaluator` seems to do exactly this, can we close this issue or is it not quite right?
