### ISSUE TITLE
[AST 6.0] Minor Arcana to CDDT

### ISSUE THREAD

**Issue by suShirow** [xivanalysis/xivanalysis#1385]
- Add to CDDT? Not sure if CDDT can accommodate. Otherwise add as another slot in `ArcanaTracking`
- Allow them to hold the card itself for 60s just until the CD is ready.

**Comment by AzariahAeroborn** [comment]
If your primary goal is to track "you used a minor arcana card 10 times and you could have gotten 12 in the fight", CDDT should work fairly well assuming you define the two minor arcana as in the same group of cooldowns (see Drill/Bioblaster in MCH -- this isn't quite the same thing as defining a CooldownGroup from the perspective of the timeline, and you need to do something specific for CDDT that's independent of the timeline stuff).

If there's other considerations about "use this card specifically under certain circumstances", CDDT won't support that.

**Comment by otocephaly** [comment]
Please see PR #1483
