### ISSUE TITLE
[AST 6.0] Macrocosmos to CDDT + additional suggestions

### ISSUE THREAD

**Issue by suShirow** [xivanalysis/xivanalysis#1387]

**Comment by otocephaly** [comment]
i've started on the CDDT portion, but not the additional suggestions portion
you'll see in the next PR

**Comment by otocephaly** [comment]
I lied
I went the wrong direction with this one lol oop

**Comment by suShirow** [comment]
Sooo I'm gonna guess you'll make a new PR for that rather than https://github.com/xivanalysis/xivanalysis/pull/1397 ?

**Comment by otocephaly** [comment]
Yeah I think that would be best so that way we can focus on what we want out of that action specifically (and since I feel like 1397 already has a lot going on)

**Comment by otocephaly** [comment]
please see new PR #1483
