### ISSUE TITLE
Tincture usage missing from Timeline module

### ISSUE THREAD

**Issue by nicholasthie** [xivanalysis/xivanalysis#1513]
In one of my logs, I used 3 tinctures in the fight with the last one being used near the end of the fight. My last tincture usage is recorded in the "Tinctures" module, but it's missing from the "Timeline" module (Medicated) . I'm guessing it's because the fight ended before the tincture ran out, but not sure. The job being used here is GNB.

Link to the log: https://xivanalysis.com/fflogs/aJ4A2GzHZXBCtjmy/82/1773

![image](https://user-images.githubusercontent.com/7281764/148433660-abb170f3-fcba-4177-ac27-409d12374278.png)
![image](https://user-images.githubusercontent.com/7281764/148433699-20fb9472-3056-4e14-b2e7-52f5a6041f60.png)

**Comment by ayyaruq** [comment]
This was fixed about 10 days ago, if the issue is still present for you please comment and we'll reopen the issue.
