### ISSUE TITLE
BLM Timeline's Procs row shows Sharpcast being consumed by Paradox under Umbral Ice

### ISSUE THREAD

**Issue by Poldovico** [xivanalysis/xivanalysis#1530]
The "Procs" row of the timeline for BLM erroneously shows UI Paradox consuming Sharpcast, although the "Sharpcast" row tracks it correctly if you open it.
It's evident in this log: https://xivanalysis.com/fflogs/8ayPA7dvMmz4pXBR/3/7 at roughly 3:15.

**Comment by Poldovico** [comment]
Adding a pic for clarity's sake:
![I'm guessing these should match](https://user-images.githubusercontent.com/41841263/148715467-a62b93d0-2dbe-42cb-906b-59cbe5091730.png)

**Comment by AkairyuGestalter** [comment]
This is fixed now as of PR #1537
