### ISSUE TITLE
Machinist GCD Uptime over 100%

### ISSUE THREAD

**Issue by Nuvm** [xivanalysis/xivanalysis#1567]
Wierd bug where the machinist clearly did not have near 100% GCD uptime but is being reported as 113.09%. They used flamethrower twice in the fight, otherwise 3 automaton queens in total in an uncleared fight.

I'd rather not directly link the xivanalysis in question publicly if possible, but would be happy to oblige in a DM.

**Comment by ackwell** [comment]
would really appreciate a log for reproduction - i think i know what it could be, but it helps to confirm.

if publicity of the log is an issue, you're able to use fflog's anonymous mode (the small icon to the right of the uploader info in this screenshot) to swap the log into anonymous mode, which will hide all the player names.
![image](https://user-images.githubusercontent.com/534235/150915677-1dd5c9f2-555a-47e4-956c-5fa0e8c4c96b.png)

**Comment by Nuvm** [comment]
https://www.fflogs.com/reports/a:tLfG39W72YFxKkvR#fight=17

There you go, took some time to figure it out but managed to anonymize it. Thanks!

**Comment by eatmorehufu** [comment]
I took a quick peek at this and it's because of `this.gcdUptime += Math.max(castTime, recastTime)`. Flamethrower cast time is 0, but recast time is 60, so every time flamethrower is used the module adds 60s of uptime.

MCH needs a custom ABC like BRD: src/parser/jobs/brd/modules/AlwaysBeCasting.ts

**Comment by eatmorehufu** [comment]
This can be closed: https://xivanalysis.com/fflogs/a:tLfG39W72YFxKkvR/17/2
