### ISSUE TITLE
DRK blood gauge calculation broken

### ISSUE THREAD

**Issue by Infiziert90** [xivanalysis/xivanalysis#1675]
Hi,

with the new patch the calculation of the blood gauge is completely off:

> 20320 blood gauge lost to an overcapped gauge.

This is the suggestion in a 6 min.

**Comment by Rjb99** [comment]
Please provide the fflog for easier debugging.

**Comment by Infiziert90** [comment]
https://xivanalysis.com/fflogs/zj23faDgbr9tk7XK/13

**Comment by ayyaruq** [comment]
This is expected. DRK currently only supports up to patch 6.08, you can see this on the player selection page of the site when you load a log or use the fight pull navigation. There's also a large banner at the top of the page telling you if a job isn't supported for the patch in the log.

**Comment by ayyaruq** [comment]
Fixed in #1683.
