### ISSUE TITLE
[BRD] [Minor] Incorrect Straight Shot Ready overwrite detection

### ISSUE THREAD

**Issue by daria-mianne** [xivanalysis/xivanalysis#1715]
See this analysis https://xivanalysis.com/fflogs/vDTBxz2KtngQYdfk/3/1 for reference

In the referenced analysis, the module claims that 2 Straight Shot Ready procs were overwritten by premature uses of Barrage. However, no such overwrites occurred. There are 3 uses of Barrage in the log, and in all 3 instances, the fact that there was no overwrite can be easily seen in the timeline near the bottom of the analysis page.

* 0:12 The first was delayed by using Pitch Perfect first to verify that no Straight Shot Ready proc had occurred, and then used when that was verified. Note that the Straight Shot Ready buff does not appear until the use of Barrage in the second oGCD slot.
* 2:15 The second was used as the first oGCD immediately following a Refulgent Arrow, meaning that it is not possible for there to have been a Straight Shot Ready proc to overwrite.
* 4:16 The third was used following a Blast Arrow, which itself had followed a Refulgent Arrow, and therefore, as with the second instance, it is not possible for there to have been a Straight Shot Ready proc to overwrite.

The same issue also occurred for the same character on the Byregot and Nald'Thal kills in the same log ( https://xivanalysis.com/fflogs/vDTBxz2KtngQYdfk/1/1 and https://xivanalysis.com/fflogs/vDTBxz2KtngQYdfk/6/1 ), although in those instances, only 1 overwrite per fight was incorrectly reported by XIVA.

**Comment by Maliziacat** [comment]
From debugging the call to `tryAddEventToOverwrites` in `stopAndSave` in core\modules\procs.tsx, we get timestamps of 705986 and 787451, with a pull timestamp of 599322. These values are in milliseconds. 705986 - 599322 = 106664, and 787451 - 599322 = 188129.

Thus the timestamps of Straight Shot Ready procs being overwritten are 1:46.664 and 3:08.129.

There are five actions that can generate Straight Shot Ready procs: Barrage, Caustic Bite, Stormbite, Iron Jaws, and Burst Shot. At 1:46, you can see your Burst Shot generated a Straight Shot Ready, but then you cast Iron Jaws which overwrote the Straight Shot Ready. Same thing happens at 3:08.

So the analysis isn't wrong! But it's certainly not informative. At the least, I think the suggestion method should mention ways to proc Straight Shot Ready. Ideally it should include timestamps.

See https://github.com/xivanalysis/xivanalysis/pull/1829 for a fix.

**Comment by hintxiv** [comment]
Thank you @Maliziacat! Closed as of #1829.
