### ISSUE TITLE
[SAM] Incorrect Kenki gain from Third Eye for multi-hit ability

### ISSUE THREAD

**Issue by HaySome22** [xivanalysis/xivanalysis#1750]
![image](https://user-images.githubusercontent.com/20825600/197303072-176e19d2-3d18-4180-8ca1-fe158bf647d2.png)

https://www.fflogs.com/reports/CmK7vaJ28x96TWkh#fight=13&type=damage-taken&view=events&source=6&ability=31060
https://xivanalysis.com/fflogs/CmK7vaJ28x96TWkh/13/6

It is counting every Abyssal Fires hit as +10 Kenki when only one instance should count.

**Comment by AzariahAeroborn** [comment]
This has been resolved as of build #21395 or later.
