### ISSUE TITLE
[RPR] very different uptime between analysis and log.

### ISSUE THREAD

**Issue by Hangovers** [xivanalysis/xivanalysis#1755]
Hi, yesterday my static logged a clear of p6s and while watching our rpr analysis on that clear I found out that he has 95.6% GCD uptime on the analysis, while it is shown as 99.60% on fflogs. I didn't investigate much so I don't really know if the right uptime is the one on the analysis (I guess it is since that specific fight had some weaving issues) but I wanted to report it to you.

https://www.fflogs.com/reports/MaGD8gJ2wny4KR9c#fight=2&type=damage-done
https://xivanalysis.com/fflogs/MaGD8gJ2wny4KR9c/2/7

**Comment by ackwell** [comment]
Thanks for reaching out!

A difference is expected. FFLogs' calculations for "Active time" are... peculiar, at best - and take into account things such as DoT ticks, buffs, etc, in a window of time as the user being "active".

While that log does have your RPR on an estimated GCD (2.50s), as they did not upload it (we can only derive precise GCD time for the logger themselves), that GCD uptime does seem correct. If you look through their timeline a bit, there's a fair few times where GCD time was dropped; i.e. the following:
![image](https://user-images.githubusercontent.com/534235/210792607-d0950cf2-2a9c-48cb-a165-568c2bc14ae7.png)

Any time between the line with a ︽ and the next cast is downtime (i.e. any time with a white background).
