### ISSUE TITLE
[PLD]Support for v6.3.x Korean logs

### ISSUE THREAD

**Issue by jhleeWEB** [xivanalysis/xivanalysis#1898]
I have been patiently waiting for Korean pld logs to be supported for quite a while now. eventhough 6.3 released in Korea the logs are still not supported by xivanalysis. I first thought that it was an ACT thing but as I looked more into it maybe It can be solved here.

I looked into the codes and I was hoping this might help a little.(maybe...)

```
ffxivgame.ver:  2023.08.03.0000.0000
Epoch timestamp: 1691049600
```

thank you for all your work :)

**Comment by suShirow** [comment]
@jhleeWEB Thank you for logging this issue, appreciate your contribution. This project is a volunteer effort and most of the contributors play on NA/JP/EU/OCE, so things like patch dates are likely to be overlooked unless contributors who have a stake in other regions chime in (via our discord server or through github).

**Comment by suShirow** [comment]
Fixed by https://github.com/xivanalysis/xivanalysis/pull/1900
