### ISSUE TITLE
Swiftcast actions not being tracked properly

### ISSUE THREAD

**Issue by fjavifabre** [xivanalysis/xivanalysis#1930]
XIVanalysis is not tracking properly which spells are being casted using Swiftcast.

Here we have a summoner analysis for a fight showing no spells were used for any of the Swiftcast:
![image](https://github.com/xivanalysis/xivanalysis/assets/17577006/03cf6f35-f253-421b-b8a9-5792305ce249)

however, if we check fight log, we can check that said summoner used Splitstream at least in 1 Swiftcast window. 
![image](https://github.com/xivanalysis/xivanalysis/assets/17577006/db1ca7dc-cb56-43ff-af4b-5eb230c50fc6)

(no cast time, also I was the one playing and used instant Splitstream there)

I checked exact same log yesterday and thing showed properly, so I assume last change in changelog maybe broke some things related to this?
![image](https://github.com/xivanalysis/xivanalysis/assets/17577006/97b2731d-115d-485c-884c-16a7484789b0)
(it seems to change things related to buff ordering)

Not trying to blame anyone, just look weird to me that same logs stopped working today.

Thanks in advance.

**Comment by AzariahAeroborn** [comment]
Thanks for the report.  Yeah, we're pretty sure that change has broken things - that change was targeted more at windows like Brotherhood (where the buff falls off before the damage event snapshots if they both happen at the same time), but it looks like we missed a side effect.  We'll take a look and update when we have it fixed.

**Comment by fjavifabre** [comment]
Thanks for the quick reply.

>We'll take a look and update when we have it fixed.

Sure, no hurry at all. Just wanted to report it in case it got under the radar since there's less people logging now that we are at last patch.

**Comment by AzariahAeroborn** [comment]
This is fixed as of build 22989 or later
