### ISSUE TITLE
Add module for potions/infusions and food

### ISSUE THREAD

**Issue by ackwell** [xivanalysis/xivanalysis#2]
Pre-cast pots only show up as the `Medicated` status, which we can't check ID for - will need to be looked into.

Likewise, Food may not have any events for an entire fight, so will need to look into how that can be checked - potentially a separate query?

**Comment by ackwell** [comment]
Partially implemented by 7eecda2.

**Comment by ackwell** [comment]
Staaaaaaaaale

**Comment by Airex** [comment]
Food is actually useless, but at least status medicated can be displayed, it makes very strong understanding how it was lined up with pty and self buffs and also could be good point for optimizations

**Comment by ackwell** [comment]
Food is not useless. Food stat buffs are sufficiently substantial to be worthwhile, and BiS sets are often built with stat tiers assuming that food is being used.

Not to mention that vitality bonus from eating even a past-tier food is _significant_, and can save your ass.

**Comment by Airex** [comment]
I mean you cant make any suggestion regarding to food as no info about gear or what food was applied. But medicated status(does not matter what exact pot) has value to be displayed in timeline. some where near raid buffs to see their intersection
