### ISSUE TITLE
Suggestion: Hide the "Don't die" suggestion if the parse is a wipe and there was only one death

### ISSUE THREAD

**Issue by Ellante** [xivanalysis/xivanalysis#207]
Hello guys

First of all, great tool, I love it!

All is in the title, and because there will always be one death in a wipe parse and it's kinda obvious not dying would have been better.

Thank you for considering this and keep up the good work!

**Comment by Toastdeib** [comment]
I'm on board with this idea - it definitely feels unnecessary to ding you on the guaranteed death if it's a wipe. I'm not sure if we currently have a way in code to distinguish between clear parses and wipe parses, but I'll dig into this tonight (or over the weekend if I end up being busy).

**Comment by Toastdeib** [comment]
Turns out we have `parser.fight.kill` as a boolean flag, so this was hilariously easy to implement. \o/

**Comment by Ellante** [comment]
Yeay thanks! \o
