### ISSUE TITLE
Add Boss mechanics to the timeline to give more context about Resource Usage

### ISSUE THREAD

**Issue by i9203** [xivanalysis/xivanalysis#2108]
Hi guys!

I think it could be a good idea to add to the timeline the boss mechanics, in order to give more context about the fight and general usage of personal Resources.

For example, right now, in the Defensive section, the site mentions about "Extra uses" in a given span of time, but without highlighting why. Having Boss mechanics in the timeline could give the reason: the user clicks on the time and in the timeline you can see which mechanic was in progress.

It could be something fixed or hardcoded for each boss, with the voices in the Timeline and nothing more. When Boss could cast two different abilities, like in M2S, I don't expect to have the exact cast in the beginning, even something like "Drop / Splash of Venom" could be good.

I know this is difficult to maintain, because every boss has its own timeline, but in theory once you add it, you should never touch it again (unless cast rename by SE, very rare).

What do you think?
Thank you for your work!

**Comment by ackwell** [comment]
per-fight configuration is something we've avoided - while yes, it likely only needs to be performed once per fight (typically), "once per fight" is infinitely more work than no work at all. with the (lack of) capacity typically on hand at patch time, i don't personally see a way forward for this without it being able to be near-entirely automatic. (minor manual upkeep is fine, ref. boss invulnerability overrides, but if it requires changes for more than a few fights every now and then, it's probably too much.)

i'll also note that skill names aren't something we can realistically use easily, as the game is in 4 (or 6, if you count non-global regions) languages. we do have action IDs, but that makes for a more fiddly process for deduplication of data &c.

for an example of a prior attempt at automating this, see https://github.com/xivanalysis/xivanalysis/pull/1628
