### ISSUE TITLE
Dancer' Technical Window below level 100

### ISSUE THREAD

**Issue by Nivyan** [xivanalysis/xivanalysis#2113]
Dancer' Technical Window reports errors for not using the expected GCDs. But the expected GCDs contain abilities above the Dancer' level.

Unsure whether this tool is used only for Level 100 encounters, if so close this.

**Comment by AkairyuGestalter** [comment]
Other than making sure the timeline can display lower-level actions, we only really support the current maximum level encounters. I'll go ahead and close this issue!
