### ISSUE TITLE
[SGE] Report missing Kardia

### ISSUE THREAD

**Issue by Lycanic** [xivanalysis/xivanalysis#2124]
Forgetting to put Kardia on **someone** seems like a 'don't die' level oversight, but completely missing Kardia healing for an entire fight isn't noted in xivanalysis currently. (I have not verified if missing it for some of the fight is noted or not)

**Comment by AkairyuGestalter** [comment]
PR #2106 will resolve this issue once someone's had a chance to review it

**Comment by AkairyuGestalter** [comment]
This has been merged and is now fixed!
