### ISSUE TITLE
Potential bug - action id property capitalization

### ISSUE THREAD

**Issue by Toastdeib** [xivanalysis/xivanalysis#23]
I noticed this while poking around in the codebase to see how it works (I'm very familiar with JS, but not so much with React). In [Gauge.js](https://github.com/xivanalysis/xivanalysis/blob/master/src/parser/jobs/war/Gauge.js#L77) for WAR analysis, it references `ACTIONS.STORMS_PATH.ID` rather than `.id`, which makes me think it's probably never hitting that block. If it works anyway through some form of React magic and this isn't actually a bug, apologies for the false alarm.

**Comment by NamelessFaceless** [comment]
You're right that it's not being called because of that. I'm not sure how we didn't catch that during the PR review. Fixed.

**Comment by ackwell** [comment]
>I'm not sure how we didn't catch that during the PR review.

'Cus I'm a bad.

**Comment by ackwell** [comment]
"Fixed" in #24. Double fixed in the rewrite once it's done.
