### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by Supamiu** [xivanalysis/xivanalysis#31]
Heya, just discovered the tool, and it's a pretty nice project 👍 

By checking code and contributions, I noticed that action names weren't translated, nor the interface.

I'm not a React dev so I don't know about what to use for the UI part, but I can provide the action names and the C# code to extract them from your game so you can update it if you're faster than me 😄 

See https://github.com/Supamiu/ffxiv-teamcraft/blob/staging/src/app/core/data/sources/actions.json for action names and https://github.com/Supamiu/ffxiv-teamcraft/tree/staging/data-extraction/XIVExtractor for the extraction code.

**Comment by NamelessFaceless** [comment]
Addressed by #81, technically. We're currently working on implementing Crowdin or some other crowd-translation service into the project, but the base is already there.

This was done pretty fast, thankfully.

**Comment by Supamiu** [comment]
Nice work ! If you need anything extracted from the game, feel free to ask, I have extracted a lot of localized stuff in order to have everything sync so I can either give you extractor source code or json files directly, everything is open source.

**Comment by ayyaruq** [comment]
This one is also prob done since Crowdin is integrated-ish and both JEDF and KR/CN are up. Actions etc are coming from xivapi. Unless 100% completion is wanted, I guess this is also done.
