### ISSUE TITLE
Barrage erroneously counted as outside RS

### ISSUE THREAD

**Issue by szjiajin** [xivanalysis/xivanalysis#359]
My friend recently states that when he do something like
GCD - (Barrage+ Raging Strikes) - Refulgent Arrow
The analysis will count that Barrage as if it is outside of RS
Can someone confirm this bug? Thank you

**Comment by ackwell** [comment]
Do you have any links to logs that exhibit the issue? It'll make the process significantly faster.

**Comment by szjiajin** [comment]
I am from CN server so I am not sure if the ability name differs inf fflogs
but here is the link
[https://xivanalysis.com/analyse/zXL2hGAxZV4YPb87/23/5/](https://xivanalysis.com/analyse/zXL2hGAxZV4YPb87/23/5/)
at 3:05 and 5:58

**Comment by MikeMatrix** [comment]
It's primarily mapped by ability ID, so that's not an issue, and FFLogs provides an option to translate the skills used in logs itself.

**Comment by ackwell** [comment]
Yumi's been informed of it. Should be a fix incoming soon:tm:.

**Comment by ayyaruq** [comment]
This should have been resolved by #1010 so I'm closing it. If this is not the case, please let us know @szjiajin.
