### ISSUE TITLE
Weaving issues about ninja

### ISSUE THREAD

**Issue by fishjump** [xivanalysis/xivanalysis#386]
Ninja can cast 2 actions in a gcd.  of course, one of them must have a faster attack animation, like jugulate, bhavacakra or smoke screen, etc.

**Comment by Toastdeib** [comment]
Double weaving is extremely ping-dependent and is usually only reliable if your ping is in the 25-30 range (or lower). If your ping is sufficiently low that you can double weave comfortably, you can ignore the weaving suggestion, but for the average user I'd prefer to keep the recommendation at single weaving. I suppose it might be worth adding a small disclaimer to the module, but I'd prefer not to make logic changes, especially not this close to the huge combat overhaul anyway. If ease of double weaving changes in ShB, I'll definitely revisit this.

**Comment by fishjump** [comment]
> Double weaving is extremely ping-dependent and is usually only reliable if your ping is in the 25-30 range (or lower). If your ping is sufficiently low that you can double weave comfortably, you can ignore the weaving suggestion, but for the average user I'd prefer to keep the recommendation at single weaving. I suppose it might be worth adding a small disclaimer to the module, but I'd prefer not to make logic changes, especially not this close to the huge combat overhaul anyway. If ease of double weaving changes in ShB, I'll definitely revisit this.

Thank you very much for your reply. Got it.
