### ISSUE TITLE
Improve GCD calculation

### ISSUE THREAD

**Issue by ackwell** [xivanalysis/xivanalysis#4]
I mean It'd be nice to get stat info from fflogs but we all know that's not gonna happen.

Currently the GCD calculator is _reasonably_ accurate, but could still use some work. This will likely be helped along by #1 - the lack of haste buff handling is currently causing some logs to estimate well under actual value.

Will also need handling for longer-than-gcd casts for jobs such as BLM, as those cases are not correctly handled as yet.

**Comment by ackwell** [comment]
The primary implementation of #1 is now in place, this is as close as it'll be getting for now. Implementation of player-provided stats will resolve this.

**Comment by hintxiv** [comment]
As of #1874 we're more or less state-of-the-art for making GCD estimations from fflogs (although there could still be areas for improvement). Longer-than-GCD casts have also been handled for awhile now. I'll close this issue in lieu of any specific flaws in the GCD estimation logic.
