### ISSUE TITLE
Consolidate DoT clip checking into core

### ISSUE THREAD

**Issue by ackwell** [xivanalysis/xivanalysis#44]
Currently got a lot of jobs copying SMN implementation.

Need to consolidate into a single implementation to make it easier to maintain the implementation w/o copypasting all over the place.

**Comment by Toastdeib** [comment]
This is something I was pondering while working on my Shadow Fang module. 100% in favor, and I'd be happy to help out if you want.

**Comment by Toastdeib** [comment]
I do believe we can close this now, forgot it was an actual open issue.

**Comment by ackwell** [comment]
You'd be right. Someone remind me to integrate it for SMN.
