### ISSUE TITLE
removed actions and Summoner

### ISSUE THREAD

**Issue by gaius12** [xivanalysis/xivanalysis#502]
Shadow Flare, Contagion, Aetherflow still there. Summoner needs to get updated asap for xivanalysis, please!

**Comment by ackwell** [comment]
xiva is a volunteer effort, and we only work as fast as people have time to contribute.

there's already some work in-flight for smn, however it's as yet incomplete, and will take time to be checked, merged, and supported.

please have some patience <img src="https://cdn.discordapp.com/emojis/424585599685623809.png?v=1" width="20" height="20"/>
