### ISSUE TITLE
issue: DNC GCD is very wrong due to steps at start

### ISSUE THREAD

**Issue by highlyunavailable** [xivanalysis/xivanalysis#534]
When doing striking dummy tests the DNC GCD is estimated to be 1.5 seconds or somewhere much lower than the real value (of 2.5). Please allow us to manually enter our "normal" GCD to recalculate clipping/uptime.

Logs:
https://xivanalysis.com/analyse/JXR673Zj1bwAfHkz/4/4/
https://xivanalysis.com/analyse/JXR673Zj1bwAfHkz/7/4/

and others within this FFLogs URL: https://www.fflogs.com/reports/JXR673Zj1bwAfHkz/

**Comment by ackwell** [comment]
Manual entry of GCD duration has been a long-standing feature I'd like to implement, but is non-trivial to implement. In the short term, I'll pass this over to some DNC devs to see if the gcd estimation can be improved.
