### ISSUE TITLE
Track Temperance usage

### ISSUE THREAD

**Issue by nivthefox** [xivanalysis/xivanalysis#598]
- [ ] Track the amount of possible uses in a fight (n).
- [ ] n-2 = green
- [ ] n-3 = yellow
- [ ] otherwise red
- [ ] Also ensure that it actually reduced damage on at least X% of the raid.

**Comment by SaltedyLevity** [comment]
Logic looks good, but i'm thinking maybe yellow as n-3 instead?
10 minute fight = 5 temp uses possible, -4 meaning they only used one; I would think that should be flagged as red? Feel free to keep it as is if you think it's better! (And if I'm interpreting the magic wrong, please let me know!)

**Comment by kkragenbrink** [comment]
@SaltedyLevity Na, you're right, 3 should be yellow.  I'll update. :) I was just making numbers up for a discussion piece when I wrote that.
