### ISSUE TITLE
SMN egi assaults incorrectly listed in OGCD checklist

### ISSUE THREAD

**Issue by Aernoth** [xivanalysis/xivanalysis#764]
In the "Use your OGCDs" section of the SMN checklist, egi assaults are listed despite being GCD actions.

**Comment by paige404** [comment]
This is a good point. Do we have a module for evaluating GCDs that have cooldowns like those?

If not, would it be better to change the module to reflect that it's tracking cooldown action uses, rather than OGCDs specifically?

**Comment by ackwell** [comment]
The module itself is relatively agnostic of what the skill is, just that it has a cooldown. It'll likely just come down to changing the wording on the checklist entry there.

If it's not configurable, probably should be. Dunno if it should be changed globally or on a case-by-case.

**Comment by Rjb99** [comment]
Samurai also does the same thing Summoner does regarding GCDs with a long cooldown using the oGCD module to handle it. Not sure if other jobs also do the same. I'd say generalize it as "Skill Usage" or something similar. I don't see a reason to make another module to handle GCDs of this nature. it's not like we would handle them differently.

**Comment by KelosPelmand** [comment]
This is (finally) be addressed in pr 834 and will likely be merged in soon to go live on the website.

**Comment by ayyaruq** [comment]
PR is merged with the updating wording.
