### ISSUE TITLE
Wrong Chinese translation for drg unbuffed stardiver

### ISSUE THREAD

**Issue by EBlaster** [xivanalysis/xivanalysis#797]
The translation of "You did not use <Stardiver> while buffed during this window." is now "你没有在这个时间窗口内使用<Stardiver>。", while it should be "你在这个时间窗口内使用的<Stardiver>没有受到增益。"

**Comment by ayyaruq** [comment]
Thanks for contributing @EBlaster, translations can be edited at https://crowdin.com/project/xivanalysis/zh-CN# if you'd like to update it. They get automatically added to the site a bit after being edited on crowdin.
