### ISSUE TITLE
Wrong blood jauge management with delirium 

### ISSUE THREAD

**Issue by SpikeOnly** [xivanalysis/xivanalysis#842]
Living Shadow is not reported as using Blood jauge while Delirium is activated

![image](https://user-images.githubusercontent.com/15890281/79121714-3bcbcd80-7d96-11ea-8f3e-154cf13c5bc5.png)

![image](https://user-images.githubusercontent.com/15890281/79121727-48502600-7d96-11ea-9b2e-dd341caf1822.png)

**Comment by nonowazu** [comment]
Looks like #843 addresses this issue – let us know if you still see any weirdness.
Thanks for reporting!
