### ISSUE TITLE
Hope there is a Chinese-Traditional translation option in Crowdin

### ISSUE THREAD

**Issue by yypccu** [xivanalysis/xivanalysis#944]
Hello contributors of xivanalysis.
This is an awesome project that helps my teammates and me a lot.
As a player who uses Traditional-Chinese and found there's no Traditional-Chinese option in the xivanalysis. It's really disappointing.
I hope i can use my experience from Steam Translation to contribute the project of xivanalysis.
If you think this is a good deal, please let me know. thx

**Comment by nonowazu** [comment]
At current, we only support the languages provided by the game itself. If we were to add one that wasn't supported by the game, it might not be unreasonable to suggest that we support additional languages which adds some amount of overhead that we cannot support at this time.
